### ISSUE TITLE
State/Province in Contribution page not being populated

### ISSUE THREAD

**Issue by verblet** [veda-consulting/uk.co.vedaconsulting.payment.ukdirectdebit#35]
CiviCRM version: 4.6.10
Drupal version: 7.41

When using the SmartDebit payment processor, the Country selector is not chaining into the State/Province selector. This means there are no states or provinces to select in a required field, so the form can never be submitted.

Not sure if this is incorrect configuration or a bug.

<img width="425" alt="screen shot 2015-12-13 at 01 56 57" src="https://cloud.githubusercontent.com/assets/6103938/11764953/e7ef5f26-a13d-11e5-9411-bff85b610dca.png">

**Comment by Kajakaran** [comment]
@verblet 
Can you test with latest version of smart debit payment processor extension?
https://github.com/veda-consulting/uk.co.vedaconsulting.payment.smartdebitdd/releases/tag/2.1.2

Thanks
Kajan
@veda-consulting

**Comment by verblet** [comment]
Thank you Kajan this works for us. We have already implemented a temporary fix in removing the State/Province field but we will deprecate that and upgrade to this latest version.
